# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### NumPy

Para importar numpy, utilize: 
import numpy as np


Você também pode utilizar: 
from numpy import *  . Isso evitará a utilização de np., mas este comando importará todos os módulos do NumPy.

Para atualizar o NumPy, abra o prompt de comando e digite: pip install numpy -U

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
np.__version__

'1.15.1'

## Criando Arrays

In [3]:
# Help
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [4]:
# Array criado a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
print(vetor1)

[0 1 2 3 4 5 6 7 8]


In [6]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho.
type(vetor1)

numpy.ndarray

In [7]:
# Usando métodos do array NumPy
vetor1.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [8]:
# Criando uma lista. Perceba como listas e arrays são objetos diferentes, com diferentes propriedades
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [9]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
type(lst)

list

In [11]:
# Imprimindo na tela um elemento específico no array
vetor1[0] 

0

In [12]:
# Alterando um elemento do array
vetor1[0] = 100

In [13]:
print(vetor1)

[100   1   2   3   4   5   6   7   8]


In [14]:
# Não é possível incluir elemento de outro tipo
vetor1[0] = 'Novo elemento'

ValueError: invalid literal for int() with base 10: 'Novo elemento'

In [15]:
# Verificando o formato do array
print(vetor1.shape)

(9,)


## Funções NumPy

In [ ]:
# A função arange cria um vetor contendo uma progressão aritmética a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [ ]:
print(vetor2)

In [ ]:
# Verificando o tipo do objeto
type(vetor2)

In [ ]:
# Formato do array
np.shape(vetor2)

In [ ]:
print (vetor2.dtype)

In [ ]:
x = np.arange(1, 10, 0.25)
print(x)

In [ ]:
print(np.zeros(10))

In [ ]:
# Retorna 1 nas posições em diagonal e 0 no restante
z = np.eye(3)

In [ ]:
z

In [ ]:
# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))

In [ ]:
d

In [ ]:
# Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])

In [ ]:
c

In [ ]:
# Array de valores booleanos
b = np.array([True, False, False, True])

In [ ]:
b

In [ ]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])

In [ ]:
s

In [ ]:
# O método linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado 
np.linspace(0, 10)

In [ ]:
print(np.linspace(0, 10, 15))

In [ ]:
print(np.logspace(0, 5, 10))

## Criando Matrizes

In [ ]:
# Criando uma matriz
matriz = np.array([[1,2,3],[4,5,6]]) 

In [ ]:
print(matriz)

In [ ]:
print(matriz.shape)

In [ ]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2,3))

In [ ]:
print(matriz1)

In [ ]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [ ]:
# A função matrix cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)

In [ ]:
matriz2

In [ ]:
type(matriz2)

In [ ]:
# Formato da matriz
np.shape(matriz2)

In [ ]:
matriz2.size

In [ ]:
print(matriz2.dtype)

In [ ]:
matriz2.itemsize

In [ ]:
matriz2.nbytes

In [ ]:
print(matriz2[2,1])

In [ ]:
# Alterando um elemento da matriz
matriz2[1,0] = 100

In [ ]:
matriz2

In [ ]:
x = np.array([1, 2])  # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype=np.float64)  # Forçamos um tipo de dado em particular

print (x.dtype, y.dtype, z.dtype)

In [ ]:
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)

In [ ]:
matriz3

In [ ]:
matriz3.itemsize

In [ ]:
matriz3.nbytes

In [ ]:
matriz3.ndim

In [ ]:
matriz3[1,1]

In [ ]:
matriz3[1,1] = 100

In [ ]:
matriz3

## Usando o Método random() do NumPy

In [ ]:
print(np.random.rand(10))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
print(np.random.rand(10))

In [ ]:
plt.show((plt.hist(np.random.rand(1000))))

In [ ]:
print(np.random.randn(5,5))

In [ ]:
plt.show(plt.hist(np.random.randn(1000)))

In [ ]:
imagem = np.random.rand(30, 30)
plt.imshow(imagem, cmap = plt.cm.hot)    
plt.colorbar()    

## Operações com datasets

In [ ]:
import os
filename = os.path.join('iris.csv')

In [ ]:
# No Windows use !more iris.csv. Mac ou Linux use !head iris.csv
!head iris.csv
#!more iris.csv

In [ ]:
# Carregando um dataset para dentro de um array
arquivo = np.loadtxt(filename, delimiter=',', usecols=(0,1,2,3), skiprows=1)
print (arquivo)

In [ ]:
type(arquivo)

In [ ]:
# Gerando um plot a partir de um arquivo usando o NumPy
var1, var2 = np.loadtxt(filename, delimiter=',', usecols=(0,1), skiprows=1, unpack=True)
plt.show(plt.plot(var1, var2, 'o', markersize=8, alpha=0.75))

## Estatística

In [ ]:
# Criando um array
A = np.array([15, 23, 63, 94, 75])

In [ ]:
# Em estatística a média é o valor que aponta para onde mais se concentram os dados de uma distribuição.
np.mean(A)

In [ ]:
# O desvio padrão mostra o quanto de variação ou "dispersão" existe em 
# relação à média (ou valor esperado). 
# Um baixo desvio padrão indica que os dados tendem a estar próximos da média.
# Um desvio padrão alto indica que os dados estão espalhados por uma gama de valores.
np.std(A)

In [ ]:
# Variância de uma variável aleatória é uma medida da sua dispersão 
# estatística, indicando "o quão longe" em geral os seus valores se 
# encontram do valor esperado
np.var(A)

In [ ]:
d = np.arange(1, 10)

In [ ]:
d

In [ ]:
np.sum(d)

In [ ]:
# Retorna o produto dos elementos
np.prod(d)

In [ ]:
# Soma acumulada dos elementos
np.cumsum(d)

In [ ]:
a = np.random.randn(400,2)
m = a.mean(0)
print (m, m.shape)

In [ ]:
plt.plot(a[:,0], a[:,1], 'o', markersize=5, alpha=0.50)
plt.plot(m[0], m[1], 'ro', markersize=10)
plt.show()

## Outras Operações com Arrays

In [ ]:
# Slicing
a = np.diag(np.arange(3))

In [ ]:
a

In [ ]:
a[1, 1]

In [ ]:
a[1]

In [ ]:
b = np.arange(10)

In [ ]:
b

In [ ]:
# [start:end:step]
b[2:9:3] 

In [ ]:
# Comparação
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

In [ ]:
np.array_equal(a, b)

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
# Somando um elemento ao array
np.array([1, 2, 3]) + 1.5

In [ ]:
# Usando o método around
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [ ]:
b = np.around(a)

In [ ]:
b

In [ ]:
# Criando um array
B = np.array([1, 2, 3, 4])

In [ ]:
B

In [ ]:
# Copiando um array
C = B.flatten()

In [ ]:
C

In [ ]:
# Criando um array
v = np.array([1, 2, 3])

In [ ]:
# Adcionando uma dimensão ao array
v[:, np.newaxis], v[:,np.newaxis].shape, v[np.newaxis,:].shape

In [ ]:
# Repetindo os elementos de um array
np.repeat(v, 3)

In [ ]:
# Repetindo os elementos de um array
np.tile(v, 3)

In [ ]:
# Criando um array
w = np.array([5, 6])

In [ ]:
# Concatenando
np.concatenate((v, w), axis=0)

In [ ]:
# Copiando arrays
r = np.copy(v)

In [ ]:
r

Conheça a Formação Cientista de Dados, um programa completo, 100% online e 100% em português, com 340 horas, mais de 1.200 aulas em vídeos e 26 projetos, que vão ajudá-lo a se tornar um dos profissionais mais cobiçados do mercado de análise de dados. Clique no link abaixo, faça sua inscrição, comece hoje mesmo e aumente sua empregabilidade:

https://www.datascienceacademy.com.br/pages/formacao-cientista-de-dados

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>