# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

In [1]:
# Pacotes dos exercícios
import numpy as np
import time as tm
import random as rn
import pandas as pd
import sqlite3 as sql

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?

array = np.array([x for x in range(1000000)])
lista = [x for x in range(1000000)]

start = tm.time()
array *= 2
end = tm.time()

print("Tempo do array: ", end - start)

start = tm.time()
lista *= 2
end = tm.time()

print("Tempo da lista: ", end - start)

Tempo do array:  0.002000093460083008
Tempo da lista:  0.028001785278320312


### Exercício 2

In [3]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

array = np.array([x for x in range(0, 10)])
print(array)

array[5:8] = 0
print(array)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 0 0 0 8 9]


### Exercício 3

In [4]:
# Crie um array de 3 dimensões e imprima a dimensão 1
dim1 = np.array([1, 2, 3])
dim2 = np.array([dim1, dim1 * 2])
dim3 = np.array([dim2 * 3, dim2 * 4])
print(dim3)
print("\nDimensão 1:\n", dim3[0])

[[[ 3  6  9]
  [ 6 12 18]]

 [[ 4  8 12]
  [ 8 16 24]]]

Dimensão 1:
 [[ 3  6  9]
 [ 6 12 18]]


### Exercício 4

In [5]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

dim = np.array([1, 2, 3])
matriz = np.array([dim, dim * 2, dim * 3])

print("Matriz M:\n", matriz, "\n")
print("M(1, y > 1):\n", matriz[:1, 1:] , "\n")
print("M(2, y > 1):\n", matriz[1:2, 1:] , "\n")
print("M(3 , y):\n", matriz[2] , "\n")

Matriz M:
 [[1 2 3]
 [2 4 6]
 [3 6 9]] 

M(1, y > 1):
 [[2 3]] 

M(2, y > 1):
 [[4 6]] 

M(3 , y):
 [3 6 9] 



### Exercício 5

In [6]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))
print("Matriz:\n", arr)

arrT = arr.T
print("\nMatriz T:\n", arrT)

Matriz:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

Matriz T:
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### Exercício 6

In [7]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

resultado = []
for x, y, bol in zip(xarr, yarr, cond):
    if bol:
        resultado.append(x)
    else:
        resultado.append(y)

resultado = np.array(resultado)
print(resultado)

[1.1 2.2 1.3 1.4 2.5]


### Exercício 7

In [8]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B
arrayA = np.arange(10)
np.save("arquivo.npy", arrayA)

arrayB = np.load("arquivo.npy")
print(arrayB)

[0 1 2 3 4 5 6 7 8 9]


### Exercício 8

In [9]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])
print(obj.unique())

['c' 'a' 'd' 'b']


### Exercício 9

In [10]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

data = resp.json()
data = pd.DataFrame(data, columns=['number', 'title', 'labels', 'state'])
data

number                                              title  \
0    22733            TST/CLN: Fixturize frame/test_analytics   
1    22731  DOC: Fix Series nsmallest and nlargest docstri...   
2    22730                     TST/CLN: Fixturize frame tests   
3    22729  Groupby Get Groups fails with "OverflowError: ...   
4    22727  Feature request: add an optional values parame...   
5    22726                  CLN: io/formats/html.py: refactor   
6    22725                         CLN/ERR: str.cat internals   
7    22724  Mismatch in Series/DataFrame boolean ops behavior   
8    22723  TST/CLN: remove duplicate data file used in te...   
9    22722              Improve TypeError message for str.cat   
10   22721    str.cat not working with binary data on Python3   
11   22720                         Reading SAS time variables   
12   22719         Python crashes with bad function arguments   
13   22717  Timedelta interpreted as int upon first insert...   
14   22714           Segfaults on Python 3.8 (CPython master)   
15   22713  BUG: astype("category") creates unreachable ob...   
16   22712         Unhandled warning from NumPy dev in median   
17   22710  BUG: Empty CategoricalIndex fails with boolean...   
18   22709  API: reconsider or warn on the non-sorting of ...   
19   22708  from_records should order dict columns similar...   
20   22707  to_clipboard has no effect in ipython (works i...   
21   22706          json_normalize raises TypeError exception   
22   22705  DataFrame.from_dict(OrderedDict(items),...) no...   
23   22704                         Support writing CSV to GCS   
24   22703  BUG: Fix dtype inconsistency when appending to...   
25   22702  ValueError in Categorical Constructor with emp...   
26   22699                               TST: Fail on warning   
27   22698  Handle FutureWarning from NumPy in Series Cons...   
28   22697  API/DEPR: 'periods' argument instead of 'n' fo...   
29   22696  BUG: fix DataFrame+DataFrame op with timedelta...   

                                               labels state  
0   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
1   [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
2   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
3   [{'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNj...  open  
4   [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
5   [{'id': 57395487, 'node_id': 'MDU6TGFiZWw1NzM5...  open  
6   [{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTE...  open  
7   [{'id': 1049312478, 'node_id': 'MDU6TGFiZWwxMD...  open  
8   [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
9   [{'id': 42670965, 'node_id': 'MDU6TGFiZWw0MjY3...  open  
10  [{'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk...  open  
11  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
12  [{'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc...  open  
13  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
14                                                 []  open  
15                                                 []  open  
16  [{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
19  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
20                                                 []  open  
21  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
22                                                 []  open  
23  [{'id': 2301354, 'node_id': 'MDU6TGFiZWwyMzAxM...  open  
24  [{'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQw...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
27  [{'id': 77550281, 'node_id': 'MDU6TGFiZWw3NzU1...  open  
28  [{'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgx...  open  
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open

### Exercício 10

In [11]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas

query = """
CREATE TABLE TESTE
(Cidade VARCHAR(20), 
 Estado VARCHAR(20),
 taxa REAL,        
 Impostos INTEGER
);"""

conn = sql.connect('banco.db')
conn.execute(query)
conn.commit()

dados = [('Natal', 'Rio Grande do Norte', 1.25, 6),
        ('Recife', 'Pernambuco', 2.6, 3),
        ('Londrina', 'Paraná', 1.7, 5)]
query = "INSERT INTO TESTE VALUES(?, ?, ?, ?)"
conn.executemany(query, dados)
conn.commit()

cursor = conn.execute('select * from teste')
arquivo = cursor.fetchall()

tabela = pd.DataFrame(arquivo, columns=[x[0] for x in cursor.description])
tabela

Cidade               Estado  taxa  Impostos
0     Natal  Rio Grande do Norte  1.25         6
1    Recife           Pernambuco  2.60         3
2  Londrina               Paraná  1.70         5

# Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>